name: CI Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' 
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Rodar ESLint
        run: npx eslint .
      
      - name: Run Duplicate Code Detector (jscpd)
        run: npx jscpd . --min-lines=5 --min-tokens=50 --ignore "**/*.json,**/*.md,node_modules/**" --fail-on-duplicate