name: CI Pipeline - Análise Estática e de Segurança

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Linter, Segurança e Análise de Qualidade
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v3
        with:
          # Necessário para o SonarCloud buscar o histórico de commits
          fetch-depth: 0

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar Dependências Python
        run: |
          python -m pip install --upgrade pip
          # Adicionar o scanner do sonar
          pip install -r requirements.txt sonar-scanner

      - name: 4. Executar Flake8 (Linter)
        run: flake8 . --count --statistics

      - name: 5. Executar Bandit (Segurança)
        run: bandit -r . -ll -iii

      - name: 6. Configurar Node.js (para ESLint)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 7. Instalar Dependências JavaScript
        run: npm install

      - name: 8. Executar ESLint
        run: npx eslint .

      # --- NOVO PASSO PARA O SONARCLOUD ---
      - name: 9. SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Fornecido pelo GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # secret