name: CI Pipeline - Análise Estática e Segurança

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Linter e Análise de Segurança
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v3

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Use a versão do Python do seu projeto

      - name: 3. Instalar Dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Executar Flake8 (Linter)
        run: |
          # --count: mostra o total de erros
          # --select=E9,F63,F7,F82: foca em erros específicos (opcional)
          # --show-source: mostra a linha do código com erro
          # --statistics: mostra estatísticas de erros
          flake8 . --count --statistics

      - name: 5. Executar Bandit (Segurança)
        run: |
          bandit -r . -ll -iii # -ll para reportar issues de média confiança pra cima, -iii para média severidade pra cima

      - name: 6. Configurar Node.js (para ESLint)
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use uma versão LTS do Node.js

      - name: 7. Instalar Dependências JavaScript
        run: npm install

      - name: 8. Executar ESLint
        run: npx eslint .